// <auto-generated />
using System;
using Crazy_zoo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crazy_zoo.Migrations
{
    [DbContext(typeof(CrazyZooContext))]
    [Migration("20251118090108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crazy_zoo.Modules.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Animals", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Capybara", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Capybara");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Dolphin", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Dolphin");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Dragon", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Dragon");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Lion", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Lion");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Parrot", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Parrot");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Shark", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Shark");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Sheep", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Sheep");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Unicorn", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Unicorn");
                });

            modelBuilder.Entity("Crazy_zoo.Animals.Whale", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.HasDiscriminator().HasValue("Whale");
                });

            modelBuilder.Entity("Crazy_zoo.Modules.CustomAnimal", b =>
                {
                    b.HasBaseType("Crazy_zoo.Modules.Animal");

                    b.Property<string>("CrazyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CustomAnimal");
                });
#pragma warning restore 612, 618
        }
    }
}
